import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppClerkProvider from "@/components/providers/AppClerkProvider";
import QueryProvider from "@/components/providers/QueryProvider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import Navigation from "@/components/shared/Navigation";
import { ScrollToTop } from "@/components/shared/ScrollToTop";
import { Toaster } from "@/components/ui/toaster";
import { NotificationProvider } from "@/context/NotificationContext";
import { TeamProvider } from "@/context/TeamContext";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Box-Drop",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className="min-h-screen bg-background">
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<AppClerkProvider>
							<NotificationProvider>
								<TeamProvider>
									<QueryProvider>
										<Navigation />
										{children}
										<Toaster />
										<ScrollToTop />
									</QueryProvider>
								</TeamProvider>
							</NotificationProvider>
						</AppClerkProvider>
					</ThemeProvider>
				</div>
			</body>
		</html>
	);
}
